[package]
name = "pyo3-ffi-check"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3-ffi-check-macro = { path = "./macro" }
memoffset = "0.6.5"

[dependencies.pyo3-ffi]
git = "https://github.com/pyo3/pyo3"
features = ["extension-module"]  # A lazy way of skipping linking in most cases (as we don't use any runtime symbols)

[workspace]
members = [
    "macro"
]

[build-dependencies]
bindgen = "0.59.2"
pyo3-build-config = { git = "https://github.com/pyo3/pyo3" }
